/* tslint:disable */
/* eslint-disable */
/**
 * Tourist agency
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarMarkIn
 */
export interface CarMarkIn {
    /**
     * 
     * @type {string}
     * @memberof CarMarkIn
     */
    name: string;
}

/**
 * Check if a given object implements the CarMarkIn interface.
 */
export function instanceOfCarMarkIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function CarMarkInFromJSON(json: any): CarMarkIn {
    return CarMarkInFromJSONTyped(json, false);
}

export function CarMarkInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarMarkIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function CarMarkInToJSON(value?: CarMarkIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

