/* tslint:disable */
/* eslint-disable */
/**
 * Tourist agency
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CarModel
 */
export interface CarModel {
    /**
     * 
     * @type {string}
     * @memberof CarModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CarModel
     */
    id: string;
}

/**
 * Check if a given object implements the CarModel interface.
 */
export function instanceOfCarModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function CarModelFromJSON(json: any): CarModel {
    return CarModelFromJSONTyped(json, false);
}

export function CarModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CarModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
    };
}

export function CarModelToJSON(value?: CarModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'id': value.id,
    };
}

