/* tslint:disable */
/* eslint-disable */
/**
 * Tourist agency
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlightIn
 */
export interface FlightIn {
    /**
     * 
     * @type {string}
     * @memberof FlightIn
     */
    departureAirport: string;
    /**
     * 
     * @type {string}
     * @memberof FlightIn
     */
    arrivalAirport: string;
    /**
     * 
     * @type {Date}
     * @memberof FlightIn
     */
    departureDateTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof FlightIn
     */
    arrivalDateTime: Date;
}

/**
 * Check if a given object implements the FlightIn interface.
 */
export function instanceOfFlightIn(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "departureAirport" in value;
    isInstance = isInstance && "arrivalAirport" in value;
    isInstance = isInstance && "departureDateTime" in value;
    isInstance = isInstance && "arrivalDateTime" in value;

    return isInstance;
}

export function FlightInFromJSON(json: any): FlightIn {
    return FlightInFromJSONTyped(json, false);
}

export function FlightInFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlightIn {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'departureAirport': json['departureAirport'],
        'arrivalAirport': json['arrivalAirport'],
        'departureDateTime': (new Date(json['departureDateTime'])),
        'arrivalDateTime': (new Date(json['arrivalDateTime'])),
    };
}

export function FlightInToJSON(value?: FlightIn | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'departureAirport': value.departureAirport,
        'arrivalAirport': value.arrivalAirport,
        'departureDateTime': (value.departureDateTime.toISOString()),
        'arrivalDateTime': (value.arrivalDateTime.toISOString()),
    };
}

