/* tslint:disable */
/* eslint-disable */
/**
 * Tourist agency
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServiceClass = {
    One: 'ONE',
    Two: 'TWO',
    Three: 'THREE',
    Four: 'FOUR',
    Five: 'FIVE'
} as const;
export type ServiceClass = typeof ServiceClass[keyof typeof ServiceClass];


export function ServiceClassFromJSON(json: any): ServiceClass {
    return ServiceClassFromJSONTyped(json, false);
}

export function ServiceClassFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceClass {
    return json as ServiceClass;
}

export function ServiceClassToJSON(value?: ServiceClass | null): any {
    return value as any;
}

